---
application:
  name: "elwarsha-miu"
  project: "Elwarsha delegates form"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "sql11411094"
  version: "5.7"
routers:
- name: "main-elwarsha-miu"
  routes:
  - application_name: "elwarsha-miu"
    paths:
    - "/*"
